Feature/jenkins create users
cloudogu/gitops-playground pull request #118
Opened 2023-06-30 06:36 UTC by CloudoguSiebels

2023-07-13 10:49 UTC, schnatterer requested changes
There are a couple of things in this PR that stand out positively:

* the Jenkins groovy shell will give us much more options and likely more stability than continuing to POST forms to Jenkins
* the Jenkins sub-command allows as to gradually migrate from shell to groovy while not having to build two static images
* the bash function `createUser` , makes it easy to test it e2e and easier to use in the next step
* HTTP retries with back-off 🥳
* good catch that we didn't use the micronaut-http-client at all 🙈
* the test using mock webserver

I mentioned annotated some things worth changing or discussion  in the code

2023-07-13 10:49 UTC, schnatterer commented on scripts/utils.sh
> +
Now that we have several entry points, I'd like to have a log statement with params. However, this would also print secrets. Any ideas?

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/cli/JenkinsCli.groovy
> +@CommandLine.Command(name = 'jenkins', description = 'CLI-tool to configure jenkins.',
Any reason why you didn't use imports like  `import picocli.CommandLine.Command ` instead of using qualified references?
IMO the code is easier to read without the repetitive `CommandLine.`

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/cli/JenkinsCli.groovy
> +        if (userManager.isUsingMatrixBasedPermissions()) {
Why does this logic belong to the CLI and not to the `UserManager`?

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/cli/JenkinsCli.groovy
> +            @CommandLine.Parameters(paramLabel = "permission", description = "The permission to grant") String permission,
Normally, I'd have said that the description of the `permission` param should contain the possible values. But since we'll plan to throw away the sub command once we're migrated the Jenkins logic from bash to groovy, this doesn't matter. Am I correct?

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/dependencyinjection/JenkinsFactory.groovy
> +    OkHttpClient okHttpClient() {
It's likely that we'll use `OkHttpClient` for other use cases then Jenkins in the future. Would simply re-use this instance and move it to a more generic Factory then, or is this client somewhat specific to Jenkins so that we should name or type it right now?

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/dependencyinjection/JenkinsFactory.groovy
> +    JenkinsFactory(JenkinsCli.OptionsMixin config) {
I'd like to discuss the usage of CLI code in the application

Until now we kept User Interface (CLI) separate from application/core like the general idea of onion architecture. See  `ApplicationConfigurator`.
We never made that decision explicit.  Let's discuss it and then decide how to proceed.

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/ApiClient.groovy
> +class ApiClient {
I'd like to have some log statements here.
E.g. trace logs, on protocol-level.
I can imagine it would be interesting to see the script that fails in the logs. Or when something fails regarding the Crumb.

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +            def realm = Jenkins.getInstance().getSecurityRealm()
Would it be possible to load the Groovy Scripts from files? That way they would be treated as proper code, not just some arbitrary string. Makes it easier to develop them as well.

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +            permissions.computeIfAbsent(jenkins.metrics.api.Metrics.VIEW) {
Why are we doing this? This looks like specific to one specific `Permission` that we enumerated and is independent of the param `permission`.

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +        log.debug("Granted user $username permission $permission")
We have debug logs 🥳 
I always put them *before*  something happens. So when something fails, I can see where it belonged to. A success message is also good, of course. Do we want both? Can we have some kind of AOP-like options in Micronaut  that allows us to do them declaratively?🙈

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +        if (result !in ["true", "false"]) { // true == was already in set, false == was not already in set
I don't understand this line, even though it's commented

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/cli/JenkinsCli.groovy
> +            userManager.grantPermission(username, UserManager.Permissions.valueOf(permission))
Wording: why do we "grant" permissions in groovy and "set" permissions on the CLI side? If there aren't any strong reasons,  I'd prefer a single term

2023-07-13 10:49 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/utils/InMemoryCookieJar.groovy
> +class InMemoryCookieJar implements CookieJar {
No tests for this class. Ratio of cost and benefit not good enough?

2023-07-13 13:25 UTC, schnatterer commented on scripts/jenkins/init-jenkins.sh
> +function createUser() {
We might want to pass `-d` or  `-x` here or otherwise we won't see any of those debug or trace logs from groovy.
Once we've done that the Jenkins subcommand will complain about 
`Unknown option: '-x' `, for example. The option is actually evaluated in `GitopsPlaygroundCliMain` so it actually works. One solution would be to add `-x` and `-d` to the `jenkins` subcommand.

2023-07-13 13:52 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +        return result == "class hudson.security.GlobalMatrixAuthorizationStrategy"
I tried this with our BCE-Instance and it has `ProjectMatrixAuthorizationStrategy`, so I can set the permissions there. Should we allow both? Would `grantPermission()` also work?

2023-07-14 08:43 UTC, CloudoguSiebels commented on scripts/utils.sh
> +
In theory, having secrets as command line arguments is bad practice anyway. You can easily leak them in logging, but more importantly you always leak them in `proc/$pid/cmdline` in a multi-user environment. When moving to config files and/or environment, we could simply log the entire command line here. However, that seems to be out of reach right now.

We could move logging the entrypoint into groovy where we have more information on what to log and what not to log. What do you think?

2023-07-14 08:44 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/cli/JenkinsCli.groovy
> +@CommandLine.Command(name = 'jenkins', description = 'CLI-tool to configure jenkins.',
No reason really. IDE didn't suggest it, and I didn't think about it. I agree though.

2023-07-14 08:56 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/cli/JenkinsCli.groovy
> +            @CommandLine.Parameters(paramLabel = "permission", description = "The permission to grant") String permission,
Yes, I want to migrate the entire Jenkins logic away from this subcommand. However, listing possible values is easy enough with `${COMPLETION-CANDIDATES}`.

2023-07-14 08:59 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/dependencyinjection/JenkinsFactory.groovy
> +    OkHttpClient okHttpClient() {
I envision to reuse the http client. Therefore, I created a separate Factory for it.

2023-07-14 09:02 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +            def realm = Jenkins.getInstance().getSecurityRealm()
We could. I decided against because

* IDEA hat support for inline code in strings
* We need to replace strings within the code, e.g. username and password when creating a user.

The latter could be solved by convention that groovy-scripts define a function that can be invoked and we concatenate the function definition and function call in the `UserManager`. 
That is complexity I didn't deem worthy right now. Do you think otherwise?

2023-07-14 09:04 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +            permissions.computeIfAbsent(jenkins.metrics.api.Metrics.VIEW) {
I missed to replace the concrete permission with $permission.

2023-07-14 09:14 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +        if (result !in ["true", "false"]) { // true == was already in set, false == was not already in set
Did my change clarify things?

In general, it is difficult to recognize script errors within the jenkins script. Therefore, I want to compare the result to known good values, and report an error on everything else.

2023-07-14 09:22 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/cli/JenkinsCli.groovy
> +        if (userManager.isUsingMatrixBasedPermissions()) {
Yes, I was thinking about this as well. Having a second opinion going in the same direction justifies a change.

2023-07-17 10:09 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/utils/InMemoryCookieJar.groovy
> +class InMemoryCookieJar implements CookieJar {
I managed to replace this class by a java.net-adapter.

2023-07-17 12:18 UTC, CloudoguSiebels commented on scripts/jenkins/init-jenkins.sh
> +function createUser() {
We evaluate the option in two places: CliMain for picocli's own logging. And `ApplicationConfigurator` for our own logging.

I don't think that tracing needs be part of the configuration as that is handled in the infrastructure layer. As a result, I moved it out of there into the parent cli class to handle the logging for all of them.

2023-07-18 11:56 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/cli/JenkinsCli.groovy
> +            @CommandLine.Parameters(paramLabel = "permission", description = "The permission to grant") String permission,
Completion candidates is a good idea. I only wonder if they will work when `paramters` is a string and not an enum at CLI-level.

But I'd leave it at that, because the CLI hopefully won't be used by end-users.

2023-07-19 12:04 UTC, schnatterer commented on scripts/utils.sh
> +
In general, logging in groovy would be a good idea.
As the different entrypoints are hopefully only temporary, I'd say we leave it as is for now.

2023-07-19 12:05 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +        log.debug("Granted user $username permission $permission")
Yeah, you're right. At this point this is probably too much effort :+1:

2023-07-19 12:06 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +        if (result !in ["true", "false"]) { // true == was already in set, false == was not already in set
Your addition to the comment clear up my prior confusion :smile: :+1:

2023-07-19 12:14 UTC, schnatterer commented on scripts/jenkins/init-jenkins.sh
> +function createUser() {
That's an interesting insight and a smart implementation :+1:

2023-07-19 12:48 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +            def realm = Jenkins.getInstance().getSecurityRealm()
:bulb: TIL that idea can inject language support via Alt + Enter and "Inject language. That'd be worth a comment. But where? Maybe at `ApiClient.runScript()`?
I can imagine that GString interpolation inside a groovy file can be complicated and loading external files makes thing more complicated in general. Let's start as is.

2023-07-19 12:52 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/dependencyinjection/JenkinsFactory.groovy
> +    JenkinsFactory(JenkinsCli.OptionsMixin config) {
That's the only remaining issue. What are your thoughts on this @CloudoguSiebels?

2023-07-19 13:04 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +            def realm = Jenkins.getInstance().getSecurityRealm()
In PhpStorm you can mark the injected code like this: 

https://www.jetbrains.com/help/phpstorm/using-language-injections.html#use-lang-annotation

I didn't find any suggestion for that using alt+enter. We could try it the same was PhpStorm does it.

2023-07-19 13:08 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/dependencyinjection/JenkinsFactory.groovy
> +    JenkinsFactory(JenkinsCli.OptionsMixin config) {
Oh, I missed to reply, sorry.

I think that DI belongs to the infrastructure layer. Therefore I think that depending on a other infrastructure code such as Picocli is okay. 

That does not address you concern regarding cli vs non-cli. One could argue that the mixin is independent from picocli as picocli only interfaces using annotations. However, I do think that this is not the appropriate solution.

I would suggest to implement a layer of abstraction regarding the configuration similar to ApplicationConfigurator. I try to change this in the evening; or you can change it yourself if you feel like it.

2023-07-19 13:13 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +            def realm = Jenkins.getInstance().getSecurityRealm()
Good point. :bulb: Reading the doc helps :see_no_evil: 
https://www.jetbrains.com/help/idea/using-language-injections.html#use-language-injection-comments
I'll add a `/* language=groovy */ ` instead of a comment!

2023-07-19 13:19 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/jenkins/UserManager.groovy
> +            def realm = Jenkins.getInstance().getSecurityRealm()
The devil in the detail :roll_eyes: 
![IDEA-lang-injection](https://github.com/cloudogu/gitops-playground/assets/1824962/9c344e70-883d-43a4-9db4-507b671aa770)

2023-07-20 07:13 UTC, merged

2023-07-20 07:15 UTC, schnatterer commented
This PR is one huge step towards getting out of our Jenkins-related Bash-hell :partying_face: