Use JGit rather than git binary
cloudogu/gitops-playground pull request #148
Opened 2023-09-05 09:18 UTC by CloudoguSiebels

2023-09-11 12:02 UTC, schnatterer requested changes
@CloudoguSiebels 
This looks very good. I'm so glad to get rid of the awful credential handling in the code and the shell-out.

The only questions I have is about the insecure handling.
The former code did not implement the insecure flag, did it? Was this a learning from errors occurred recently?

2023-09-11 12:02 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/scmm/jgit/InsecureCredentialProvider.groovy
> +class InsecureCredentialProvider extends CredentialsProvider {
Could you please add some comment here? The checks for prompts look a bit awkward though I'm sure you thoroughly checked before that there is no easier option.  An answer to the question "Why was this implemented that way?" would surely be helpful for future reference.

2023-09-11 12:25 UTC, CloudoguSiebels commented
> The former code did not implement the insecure flag, did it? Was this a learning from errors occurred recently?

Yes it did by using an environment variable. 

https://github.com/cloudogu/gitops-playground/blob/main/scripts/apply.sh#L71

*This* wasn't failing recently. However, recent failures prompted me to test this case :)

2023-09-11 12:26 UTC, CloudoguSiebels commented on src/main/groovy/com/cloudogu/gitops/scmm/jgit/InsecureCredentialProvider.groovy
> +class InsecureCredentialProvider extends CredentialsProvider {
Yep, will do. 

According to threads in Stackoverflow, JGit was developed with a interactive UI in mind.

2023-09-11 14:31 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/scmm/jgit/InsecureCredentialProvider.groovy
> +class InsecureCredentialProvider extends CredentialsProvider {
:bulb: I think it's helpful to add a link to SO in the comments.

2023-09-12 09:06 UTC, schnatterer approved these changes

2023-09-12 09:46 UTC, merged