Added email parameters for Grafana and ArgoCD
cloudogu/gitops-playground pull request #164
Opened 2023-11-24 09:22 UTC by movray

2023-12-04 16:06 UTC, schnatterer requested changes
My suggestion is that you

1. adopt from  
  `config.features['monitoring']['grafana']['emailFrom']` to  
  `config.features['monitoring']['grafanaEmailFrom'] .`  
  This will fix the config file and follow the naming pattern used by the existing `grafanaUrl`.
2. Move the defaults for the 5 parameters to `ApplicationConfigurator.DEFAULT_VALUES` and remove the `<#if x?has_content>` blocks from the templates. This makes them easier to maintain and follows our current approach to centralize all defaults in `ApplicationConfigurator`.

2023-12-04 16:06 UTC, schnatterer commented on argocd/argocd/argocd/values.ftl.yaml
> +      <#if argocd.emailFrom?has_content>
From a functional point of view it's valid to implement the default value here.

In my opinion, this hides the defaults deep in the code.
That's why we implemented all other defaults centrally in `ApplicationConfigurator.DEFAULT_VALUES`.

2023-12-06 15:05 UTC, movray commented on src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy
> +         String grafanaEmailFrom = ""
corrected in code

2023-12-08 16:25 UTC, schnatterer approved these changes

2023-12-08 16:33 UTC, schnatterer commented
Had to fix apply.sh. 
Then  tested these use cases
* config file, works with dev image (prod has known issue #166) 
* params, works
* defaults, works

Works means the values are written to the expected YAML files in the repositories.
I also watched some actual emails in MailHog.

Only question that remains is: 
**Does Grafana pick up the `grafana-email-to` at all?** I could not find it in Grafana's UI.

Test commands

**config-file:**
``` 
 docker run --rm  -u $(id -u) \
    -v ~/.config/k3d/kubeconfig-gitops-playground.yaml:/home/.kube/config \
  -v $PWD/config.yaml:/config/config.yaml \
    --net=host \                                                                                                                                                                                                  gitops-playground:dev --yes --argocd --base-url=http://localhost  --monitoring -x --config-file=/config/config.yaml --mail
```

with `config.yaml`
```
features: 
  argocd: 
    emailFrom: from@argo.cd
    emailToAdmin: to-admin@argo.cd
    emailToUser: to-user@argo.cd
  monitoring: 
    grafanaEmailFrom: from@grafa.na
    grafanaEmailTo: to@grafa.na
```

**params:**
```
docker run --rm  -u $(id -u) \
   -v ~/.config/k3d/kubeconfig-not-bound.yaml:/home/.kube/config \
    --net=host \
   gitops-playground:dev --yes --argocd --base-url=http://localhost  --monitoring -x --mail --argocd-email-from=from@argo.cd --argocd-email-to-admin=to-admin@argo.cd --argocd-email-to-user=to-user@argo.cd --grafana-email-from=from@grafa.na --grafana-email-to=to@grafa.na
```

2023-12-12 09:14 UTC, schnatterer commented
We found out that Grafana not picking up the value that is now `grafana-email-to` is a bug that existed before. A fix is already under way with our upcoming story for external mail server support.

2023-12-12 09:14 UTC, merged