added feature configure external Mailserver, corrected settings for g…
cloudogu/gitops-playground pull request #170
Opened 2023-12-17 17:02 UTC by movray

…rafana contact point when internal Mailserver is used, added pependency check if internal or externa Mailserver is used

2023-12-22 14:07 UTC, schnatterer commented on scripts/apply.sh
> +    --long help,config-file:,config-map:,output-config-file,destroy,argocd,argocd-url:,debug,remote,base-url:,username:,password:,jenkins-url:,jenkins-username:,jenkins-password:,jenkins-metrics-user
Please add colons after all email-related params.

This way the user can choose to pass the params with or without equals sign.

2023-12-22 14:11 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy
> +    MailHogUrlIfNotBaseUrl mailHogUrlIfNotBaseUrl
IMO we don't need this. It's OK to set both mailhog-url and base-url.
With base-url you set defaults for all ingresses. If you want to have a custom ingress only for mailho, you can also set mailhog-url,

2023-12-22 14:17 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/config/ApplicationConfigurator.groovy
> +//        if (newConfig.['features']['mail']['mailhog'] || smt-paramer)
Why didn't you set mail.active here:
config.features['mail']['mailhog'] || config.features['mail']['externalMailserver'] ? true : false

This way you could have left the mail.active in ArgoCD and Prometheus as they were.

2023-12-22 14:18 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy
> +                            active: config.features['mail']['mailhog'],
This way we will not get any `notifications.argoproj.io/subscribe.email` annotation when we use the external mail server. Please use mail.active here.

2023-12-22 14:20 UTC, schnatterer commented
Please add new params also to Schema, so they can be configured via config file

2024-01-09 09:33 UTC, movray commented on src/main/groovy/com/cloudogu/gitops/features/argocd/ArgoCD.groovy
> +                            active: config.features['mail']['mailhog'],
changed

2024-01-22 20:38 UTC, schnatterer requested changes
We made some progress!
I still see some issues here, though. Sorry, @movray .

2024-01-22 20:38 UTC, schnatterer commented on applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml
> +    GF_SMTP_HOST: ${mail.externalMailserver}:${mail.externalMailserverPort}
What happens if port is not set? Shouldn't you check if it is set here?

You should probably also only set Env Vars for user and password if  externalMailserverUser and externalMailserverPassword are set.

Same goes for Argo CD.

Please write tests.

2024-01-22 20:38 UTC, schnatterer commented on applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml
> + <#if mail.externalMailserver?has_content>
Why do you use `has_ _content` here and not `??

2024-01-22 20:38 UTC, schnatterer commented on argocd/argocd/argocd/values.ftl.yaml
> +      <#if mail.externalMailserver?has_content>
See prometheus stack

2024-01-22 20:38 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/cli/GitopsPlaygroundCli.groovy
> +                                externalMailserver : smtpAddress,
Using two different names for the same thing makes things more complex than necessary.

We as developers will know have to remember that
`externalMailserver` is synonym to `smtpAddress` and the same goes for port, user and password. 

And this causes confusion! You can already see it in Schema.groovy (see bellow).
We should use the same terms for the same things.

This would either mean using `smtp*` internally or `external-mail-server-*` on the CLI. I don't care which, prefer the the less time consuming one :grimacing:

2024-01-22 20:38 UTC, schnatterer commented on src/main/groovy/com/cloudogu/gitops/config/schema/Schema.groovy
> +         boolean mailhog = true
In order for this to work the hierarchy of the objects in this class has to match the hierarchy of the `config` map.

For example:
`config` map: contains
* features.mail.url
* features.mail.externalMailserver

In `Schema.groovy` we have: 
* features.mail.mailhogUrl
* features.mail.smtpAddress

This leads to the values from config file to being ignored.

I know, the solution here is somewhat complex and we had errors like this before.

So I added a test: `ApplicationConfiguratorTest.config file has only fields that are present in default values` that fails. Please fix it.

2024-02-02 09:57 UTC, schnatterer commented on argocd/argocd/argocd/values.ftl.yaml
> +      <#if mail.externalMailserver?has_content>
`has_content` checks for not null and empty string, `??` not null and `true` for booleans.
In our case `has_content` is probably more reliable, because we often use empty string as default value.

2024-02-02 09:59 UTC, schnatterer commented on applications/cluster-resources/monitoring/prometheus-stack-helm-values.ftl.yaml
> + <#if mail.externalMailserver?has_content>
has_content checks for not null and empty string, ?? not null and true for booleans.
In our case has_content is probably more reliable, because we often use empty string as default value.

2024-02-02 13:07 UTC, schnatterer approved these changes

2024-02-02 15:18 UTC, schnatterer commented
I tested this

```
scripts/init-cluster.sh --bind-ingress-port=80  && docker run --rm -u $(id -u) \                                     
    -v ~/.config/k3d/kubeconfig-gitops-playground.yaml:/home/.kube/config \
    --net=host gitops-playground --yes --argocd --base-url=http://localhost  --monitoring --vault=dev --mailhog --mailhog-url http://hog.localhost -x  --argocd-email-from=from@argo.cd --argocd-email-to-admin=to-admin@argo.cd \
  --argocd-email-to-user=to-user@argo.cd --grafana-email-from=from@grafa.na --grafana-email-to=to@grafa.na
```

and  this

``` 
 scripts/init-cluster.sh --bind-ingress-port=80  \
&& docker run --rm -u $(id -u) \
    -v ~/.config/k3d/kubeconfig-gitops-playground.yaml:/home/.kube/config \
       -v $(pwd)/gitops-playground.yaml:/config/gitops-playground.yaml \
    --net=host gitops-playground --yes --argocd --base-url=http://localhost  --monitoring --vault=dev --mailhog --mailhog-url http://hog.localhost -x --config-file=/config/gitops-playground.yaml
``` 

with this config file

```yaml
features:   
  mail:  
    mailhog: true # should be ignored  
    smtpAddress: 'smtp.gmail.com'
    smtpPort: 465
    smtpUser: USER
    smtpPassword: APP_PW
  argocd:  
    emailFrom: USER
    emailToAdmin: other email
    emailToUser: other email
  monitoring:  
    grafanaEmailFrom: USER
    grafanaEmailTo: other email
```

And everything seems to work.

There is one thing we should improve, though: The `smtpPassword` is stored in plain text in git 😱!

In argocd we can avoid this by using the [argocd-notifications-secret](
https://github.com/argoproj/argo-cd/blob/v2.9.5/docs/operator-manual/notifications/index.md#getting-started). But what about Grafana?

2024-02-05 07:57 UTC, merged